### ISSUE TITLE
got "mixed content - blocked" error message from firefox & chrome

### ISSUE THREAD

**Issue by miconx** [meteor-factory/meteor-admin-lte#2]
GET 
http://127.0.0.1:3000/packages/mfactory_admin-lte/css/AdminLTE.min.css

and 

GET 
http://127.0.0.1:3000/packages/mfactory_admin-lte/css/skins/skin-blue.min.css

will be blocked on sites which use https ...

**Comment by mpowaga** [comment]
We are using [Meteor.absoluteUrl](http://docs.meteor.com/#/full/meteor_absoluteurl), maybe your `ROOT_URL` isn't `https`?

**Comment by miconx** [comment]
yes this was the culprit, thanks!

**Comment by Gib-git** [comment]
How to change this?
