### ISSUE TITLE
Remove Bootstrap dependency

### ISSUE THREAD

**Issue by kop** [meteor-factory/meteor-admin-lte#5]
Hi, thanks for a package.

In `package.json` you have `twbs:bootstrap` dependency which makes this package unusable with other Bootstrap packages (e.g. I'm using [nemo64/bootstrap](https://atmospherejs.com/nemo64/bootstrap)).

Maybe it will be better to remove this dependency and allow users to connect any Bootstrap package they want?

**Comment by loredanacirstea** [comment]
I see that you have removed the bootstrap dependency in the last version, but it seems you did not update the atmosphere package. Doing a `meter add mfactory:admin-lte` still adds `twbs:bootstrap`

**Comment by jay-depot** [comment]
@loredanacirstea hopefully #14 will get their attention ;-)
